export const DEFAULT_CURRENCY = 'USD';

export const DEFAULT_CURRENCIES = [
	// Most common currencies first
	{ text: 'Euro (€)', value: 'EUR' },
	{ text: 'United States Dollar ($)', value: 'USD' },
	{ text: 'British Pound (£)', value: 'GBP' },
	{ text: 'Japanese Yen (¥)', value: 'JPY' },
	{ text: 'Chinese Yuan (¥)', value: 'CNY' },

	// Rest alphabetically
	{ text: 'Albanian Lek (L)', value: 'ALL' },
	{ text: 'Arabic Emirates Dirham (د.إ)', value: 'AED' },
	{ text: 'Argentine Peso ($)', value: 'ARS' },
	{ text: 'Australian Dollar (A$)', value: 'AUD' },
	{ text: 'Bengali-Bangladeshi Taka (৳)', value: 'BDT' },
	{ text: 'Brazilian Real (R$)', value: 'BRL' },
	{ text: 'Bulgarian Lev (лв)', value: 'BGN' },
	{ text: 'Canadian Dollar (C$)', value: 'CAD' },
	{ text: 'Chilean Peso ($)', value: 'CLP' },
	{ text: 'Colombian Peso ($)', value: 'COP' },
	{ text: 'Croatian Kuna (kn)', value: 'HRK' },
	{ text: 'Czech Koruna (Kč)', value: 'CZK' },
	{ text: 'Danish Krone (kr)', value: 'DKK' },
	{ text: 'Egyptian Pound (E£)', value: 'EGP' },
	{ text: 'Georgian Lari (₾)', value: 'GEL' },
	{ text: 'Hong Kong Dollar (HK$)', value: 'HKD' },
	{ text: 'Hungarian Forint (Ft)', value: 'HUF' },
	{ text: 'Icelandic Króna (kr)', value: 'ISK' },
	{ text: 'Indian Rupee (₹)', value: 'INR' },
	{ text: 'Indonesian Rupiah (Rp)', value: 'IDR' },
	{ text: 'Iranian Rial (﷼)', value: 'IRR' },
	{ text: 'Israeli New Shekel (₪)', value: 'ILS' },
	{ text: 'Korean Won (₩)', value: 'KRW' },
	{ text: 'Malaysian Ringgit (RM)', value: 'MYR' },
	{ text: 'Mexican Peso ($)', value: 'MXN' },
	{ text: 'Moroccan Dirham (د.م.)', value: 'MAD' },
	{ text: 'New Zealand Dollar (NZ$)', value: 'NZD' },
	{ text: 'Norwegian Krone (kr)', value: 'NOK' },
	{ text: 'Pakistani Rupee (₨)', value: 'PKR' },
	{ text: 'Philippine Peso (₱)', value: 'PHP' },
	{ text: 'Polish Złoty (zł)', value: 'PLN' },
	{ text: 'Romanian Leu (lei)', value: 'RON' },
	{ text: 'Russian Ruble (₽)', value: 'RUB' },
	{ text: 'Saudi Riyal (﷼)', value: 'SAR' },
	{ text: 'Serbian Dinar (дин.)', value: 'RSD' },
	{ text: 'Singapore Dollar (S$)', value: 'SGD' },
	{ text: 'South African Rand (R)', value: 'ZAR' },
	{ text: 'Swedish Krona (kr)', value: 'SEK' },
	{ text: 'Swiss Franc (CHF)', value: 'CHF' },
	{ text: 'Thai Baht (฿)', value: 'THB' },
	{ text: 'Turkish Lira (₺)', value: 'TRY' },
	{ text: 'Ukrainian Hryvnia (₴)', value: 'UAH' },
	{ text: 'Vietnamese Dong (₫)', value: 'VND' },
];
